travis:
  secure:
    BINSTAR_TOKEN: iyS8EwI0kXIfTLIXmq/z69BnaCjt84qNKFuBwucdMFeZ91hw6gB0gryZ2GcVq7ezN2FygoiEfA9UkPPIA/z5S52W3aVJBlLljNh/4P5D8W2RxXQHfbEczZHAWHT2IjySE2k76C9qcmhTNngEq/YPzCMPYdRctf2R3yRaFd6ZsldDG0NMUtRKIx+WEHs9MZv5hAwqerf8YV9l2RoBPIwjgp+YNal/K1C/zj9ktL+OQ7HvNL3Q194ysYapFIvtNjusJQPZ1k5Uz2CpNc/fZPhQxKJ2TBKanh0es2nHUTvRfZibcyL44APIfrYKKHHDyQmDiifnHkeEI2Oq9oYF1K24ZrUZiMzumDxmDtkzBIfWy/t4Gpmt0tOTeT6h9hCn4XqMOj6rfnnuInou8MwC0TLLpYh60769b+W4q/kRlM1UQK55HPTr6CYjVZ2iJWphClEKc/058tKHFkyP7bp9i+lwxhAwwgk0UHt+A/fTcXHVflkCQ195lr9AZGHSD1HJPWMbmERoTBb4978V1r7ojAaQSxo/x57cxgB4uSVHtZygEQlv5KpyHTyz2cTQOQBU4GQ4E7KYXDYIoUL4vcb/MK10wKg9ftiXUIwxPzGTnBLWULsYVQWjXImBInyIcdcaIwB2FLXualRGEhGeZkkDaRxgY0anzqFEH77Yoj2ve8LQ2S8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
